FROM scratch

LABEL maintainer="PortaOne Inc."
LABEL summary="Image for SecurePay payment processor"

ARG PORTA_GIT_COMMIT=unspecified
ARG PORTA_GIT_TAG=unspecified
ARG PORTA_GIT_BRANCH=master
ARG PORTA_APP_NAME='ba-pp-secure-pay'

ENV PORTA_GIT_TAG=$PORTA_GIT_TAG
ENV PORTA_GIT_COMMIT=$PORTA_GIT_COMMIT
ENV PORTA_APP_NAME=$PORTA_APP_NAME

LABEL PORTA_GIT_TAG=$PORTA_GIT_TAG
LABEL PORTA_GIT_COMMIT=$PORTA_GIT_COMMIT
LABEL PORTA_GIT_BRANCH=$PORTA_GIT_BRANCH

ADD ba-pp-SecurePay ba-pp-SecurePay
EXPOSE 7777
ENTRYPOINT ["/ba-pp-SecurePay"]
