apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ba-pp-SecurePay
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ba-pp-SecurePay
  template:
    metadata:
      labels:
        app: ba-pp-SecurePay
    spec:
      containers:
        - name: ba-pp-SecurePay
          image: maxkondr/ba-pp-secure-pay
          ports:
          - name: grpc
            containerPort: 7777
          env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
